# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(verbose_name='UpdateAt')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Header'),
        ),
    ]
